{
  "openapi": "3.0.1",
  "info": {
    "title": "Reservations API",
    "version": "v1"
  },
  "servers": [
    {
      "url": "{server}:{port}/reservations",
      "description": "Base server URL for Reservations API",
      "variables": {
        "server": {
          "default": "http://localhost",
          "description": "Server host"
        },
        "port": {
          "enum": [
            "8080",
            "8080"
          ],
          "default": "8080",
          "description": "Server port"
        }
      }
    }
  ],
  "paths": {
    "/{reservation_id}": {
      "put": {
        "tags": [
          "Reservations"
        ],
        "operationId": "updateReservation",
        "parameters": [
          {
            "name": "reservation_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "checkinDate": {
                    "type": "string"
                  },
                  "checkoutDate": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Reservation updated successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer",
                      "format": "int32"
                    },
                    "room": {
                      "type": "object",
                      "properties": {
                        "number": {
                          "type": "integer",
                          "format": "int32"
                        },
                        "type": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "integer",
                              "format": "int32"
                            },
                            "name": {
                              "type": "string"
                            },
                            "guestCapacity": {
                              "type": "integer",
                              "format": "int32"
                            },
                            "price": {
                              "type": "number",
                              "format": "double"
                            }
                          }
                        }
                      }
                    },
                    "checkinDate": {
                      "type": "string",
                      "format": "date"
                    },
                    "checkoutDate": {
                      "type": "string",
                      "format": "date"
                    },
                    "user": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "mobileNumber": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Reservations"
        ],
        "operationId": "deleteReservation",
        "parameters": [
          {
            "name": "reservation_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Reservation deleted successfully"
          }
        }
      }
    },
    "/": {
      "post": {
        "tags": [
          "Reservations"
        ],
        "operationId": "createReservation",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "checkinDate": {
                    "type": "string"
                  },
                  "checkoutDate": {
                    "type": "string"
                  },
                  "roomType": {
                    "type": "string"
                  },
                  "user": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "email": {
                        "type": "string"
                      },
                      "mobileNumber": {
                        "type": "string"
                      }
                    }
                  },
                  "rate": {
                    "type": "number",
                    "format": "double"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Reservation created successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer",
                      "format": "int32"
                    },
                    "room": {
                      "type": "object",
                      "properties": {
                        "number": {
                          "type": "integer",
                          "format": "int32"
                        },
                        "type": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "integer",
                              "format": "int32"
                            },
                            "name": {
                              "type": "string"
                            },
                            "guestCapacity": {
                              "type": "integer",
                              "format": "int32"
                            },
                            "price": {
                              "type": "number",
                              "format": "double"
                            }
                          }
                        }
                      }
                    },
                    "checkinDate": {
                      "type": "string",
                      "format": "date"
                    },
                    "checkoutDate": {
                      "type": "string",
                      "format": "date"
                    },
                    "user": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "mobileNumber": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{userId}": {
      "get": {
        "tags": [
          "Reservations"
        ],
        "operationId": "getUserReservations",
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User reservations fetched successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer",
                        "format": "int32"
                      },
                      "room": {
                        "type": "object",
                        "properties": {
                          "number": {
                            "type": "integer",
                            "format": "int32"
                          },
                          "type": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "integer",
                                "format": "int32"
                              },
                              "name": {
                                "type": "string"
                              },
                              "guestCapacity": {
                                "type": "integer",
                                "format": "int32"
                              },
                              "price": {
                                "type": "number",
                                "format": "double"
                              }
                            }
                          }
                        }
                      },
                      "checkinDate": {
                        "type": "string",
                        "format": "date"
                      },
                      "checkoutDate": {
                        "type": "string",
                        "format": "date"
                      },
                      "user": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "string"
                          },
                          "name": {
                            "type": "string"
                          },
                          "email": {
                            "type": "string"
                          },
                          "mobileNumber": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/roomTypes": {
      "get": {
        "tags": [
          "Reservations"
        ],
        "operationId": "getRoomTypes",
        "parameters": [
          {
            "name": "checkinDate",
            "in": "query",
            "schema": {
              "type": "string",
              "format": "date",
              "default": "2024-02-15T15:00:38.122Z"
            },
            "required": false
          },
          {
            "name": "checkoutDate",
            "in": "query",
            "schema": {
              "type": "string",
              "format": "date",
              "default": "2024-02-16T15:00:38.122Z"
            },
            "required": false
          },
          {
            "name": "guestCapacity",
            "in": "query",
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 1
            },
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "Available room types fetched successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer",
                        "format": "int32"
                      },
                      "name": {
                        "type": "string"
                      },
                      "guestCapacity": {
                        "type": "integer",
                        "format": "int32"
                      },
                      "price": {
                        "type": "number",
                        "format": "double"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "UpdateReservationRequest": {
        "type": "object",
        "properties": {
          "checkinDate": {
            "type": "string"
          },
          "checkoutDate": {
            "type": "string"
          }
        }
      },
      "Reservation": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "room": {
            "type": "object",
            "properties": {
              "number": {
                "type": "integer",
                "format": "int32"
              },
              "type": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer",
                    "format": "int32"
                  },
                  "name": {
                    "type": "string"
                  },
                  "guestCapacity": {
                    "type": "integer",
                    "format": "int32"
                  },
                  "price": {
                    "type": "number",
                    "format": "double"
                  }
                }
              }
            }
          },
          "checkinDate": {
            "type": "string",
            "format": "date"
          },
          "checkoutDate": {
            "type": "string",
            "format": "date"
          },
          "user": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "email": {
                "type": "string"
              },
              "mobileNumber": {
                "type": "string"
              }
            }
          }
        }
      },
      "Room": {
        "type": "object",
        "properties": {
          "number": {
            "type": "integer",
            "format": "int32"
          },
          "type": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer",
                "format": "int32"
              },
              "name": {
                "type": "string"
              },
              "guestCapacity": {
                "type": "integer",
                "format": "int32"
              },
              "price": {
                "type": "number",
                "format": "double"
              }
            }
          }
        }
      },
      "RoomType": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string"
          },
          "guestCapacity": {
            "type": "integer",
            "format": "int32"
          },
          "price": {
            "type": "number",
            "format": "double"
          }
        }
      },
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "mobileNumber": {
            "type": "string"
          }
        }
      },
      "ReservationRequest": {
        "type": "object",
        "properties": {
          "checkinDate": {
            "type": "string"
          },
          "checkoutDate": {
            "type": "string"
          },
          "roomType": {
            "type": "string"
          },
          "user": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "email": {
                "type": "string"
              },
              "mobileNumber": {
                "type": "string"
              }
            }
          },
          "rate": {
            "type": "number",
            "format": "double"
          }
        }
      },
      "UserDto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "mobileNumber": {
            "type": "string"
          }
        }
      }
    }
  }
}